name: Strategy
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            version: ["1.12", "2.23", "3.32"]
            sistema_operativo: ["Windows", "Linux", "MacOS"]

        steps:
          - name: Mostrar mensaje
            run: echo "${{ matrix.version }} - ${{ matrix.sistema_operativo }}"