name: Deploy to server
on: push

jobs:
  first_job:
    name: Primer JOB
    runs-on: ubuntu-latest

    env:
      NAME: ADRIAN

    steps:
      - name: Hola mundo
        run: echo "Hola mundo $NAME"
        
      - name: Action
        uses: actions/checkout@v4
        
      - name: Working dir after action
        run: ls -al

  second_job:
    name: Segundo JOB
    if: ${{ github.ref != 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo"