name: Deploy to server
on: push

jobs:
  first_job:
    name: Primer JOB
    runs-on: ubuntu-latest

    env:
      NAME: ADRIAN

    outputs:
      salida: ${{ steps.step_1.outputs.mi_variable }}

    steps:
      - name: Hola mundo
        run: echo "Hola mundo $NAME"
        
      - name: Action
        uses: actions/checkout@v4
        
      - name: Working dir after action
        run: ls -al

      - name: Working dir
        id: step_1
        run: echo "mi_variable=Hola mundo" >> $GITHUB_OUTPUT

      - name: Obtener mensaje de step anterior. Aquí puede ir cualquier contenido.
        run: echo "${{ steps.step_1.outputs.mi_variable }}"

      - name: Generar archivo
        run: |
          echo "Archivo generado de prueba: HOLA" >> test.log
      
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log

  second_job:
    name: Segundo JOB
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest

    env:
      SALIDA: ${{ needs.first_job.outputs.salida }} 

    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo"

      - name: Mensaje traido desde first_job
        run: echo "$SALIDA"